#!/bin/bash



DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

## install homebrew

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1:33m'
NC='\033[0m' # No Color


  printf "Do you want to install ${RED} Homebrew itself${NC}?\n"
  read -r -p "Please confirm with [y/N] " response
  case $response in
    [yY][eE][sS]|[yY])
      echo -e "${GREEN}installing homebrew${NC}"
      /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      ;;
    *)
      echo -e "${YELLOW}skipping homebrew${NC}"
      ;;
  esac


packages="
git
vim
bash-completion
bash-git-prompt
rbenv
ruby-build
autojump
the_silver_searcher
direnv
nodenv
awscli
"

options=("YES" "NO")

for package in $packages; do
  printf "Do you want to install ${RED}$package${NC}?\n"
  read -r -p "Please confirm with [y/N] " response
  case $response in
    [yY][eE][sS]|[yY])
      echo "${GREEN}installing $package${NC}"
      brew install $package
      ;;
    *)
      echo -e "${YELLOW}skipping $package${NC}"
      ;;
  esac
done
